---
- name: Nginx | Install Nginx
  sudo: yes
  apt: pkg=nginx
  tags: nginx

- name: Nginx | Setup reverse proxy
  sudo: yes
  template: src=default dest=/etc/nginx/sites-available
  tags: nginx

- name: Nginx | start nginx
  sudo: yes
  service: name=nginx state=restarted
  tags: nginx